### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by mapsam** [cybersea/efh2016-metrics#17]
Adding tooltips could be a useful UI addition, especially for the new buttons coming up in #3 

Example at dropchop:

![screen shot 2016-10-17 at 12 24 02 pm](https://cloud.githubusercontent.com/assets/1943001/19452112/9f67136e-9464-11e6-810b-d1a829a46c16.png)

This is part of #16

**Comment by mapsam** [comment]
@cybersea how do you feel about something like this?

![screen shot 2016-10-17 at 2 08 14 pm](https://cloud.githubusercontent.com/assets/1943001/19455770/3133bd16-9473-11e6-9284-6c190203d586.png)

**Comment by cybersea** [comment]
@mapsam that looks cool!   I'm also ok with check boxes, since I think they are a more "standard" UI for map layer visibility.   And, then maybe that UI component wouldn't need a tool tip.   What do you think?  

I was thinking the Proposal selection/unselection buttons might need an icon and a tool tip because of space limitations.

I also added a leaflet control for the reference layers (Issue #10), which has the checkboxes.   Shall we make those two controls consistent?   (either the sliding button like you have or checkboxes).   Or is it ok to have them look different because they serve different purposes.

Many questions for your advice, thought, input.

**Comment by mapsam** [comment]
Great questions and observations! I like the idea of keeping checkboxes for toggling layers on/off - let's move to those. Here's a screenshot:

![screen shot 2016-10-17 at 3 05 31 pm](https://cloud.githubusercontent.com/assets/1943001/19457439/334216c2-947b-11e6-813b-713857326690.png)

Still unsure which icons/buttons should be for selecting the entire layer. I'm considering something similar to Adobe, where it's just a highlighted box vs. empty box: 

![screen shot 2016-10-17 at 3 06 39 pm](https://cloud.githubusercontent.com/assets/1943001/19457479/5550ed92-947b-11e6-8550-8bb2af19c86c.png)

Can we turn it into a single button, where you either toggle all layers selected or unselected?

**Comment by cybersea** [comment]
Yeah -- the icon is tough.  I think your idea sounds good.  And, the tool tips will be helpful.   

A single toggle would be ideal, but I realized that a user might have interactively selected or unselected some individual polygons, so it could be in a state where some polygons from a proposal are selected and some are not.   Then it would not be obvious if a user wants to add all the remaining polygons for that proposal, or to remove the currently selected polygons from that Proposal.  See Issue #3
