### ISSUE TITLE
Polygon Info box Overflows onto buttons on right tab

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#26]

**Comment by cybersea** [comment]
Real estate on the right panel is valuable. @mapsam do you have time for this?  Or give me some hints (i.e. css foo.....)

**Comment by mapsam** [comment]
@cybersea an alternative would be to add the information to a popup on the map as you hover over polygons instead of populating data on the right sidebar. This would give you more horizontal real estate.

![img_2764](https://cloud.githubusercontent.com/assets/1943001/19985959/261a519e-a1d2-11e6-87ff-6ffed5304e20.jpg)

**Comment by mapsam** [comment]
WOW I LABELLED LEFT AND RIGHT INCORRECTLY

I'm going to keep that one for the lol's

**Comment by cybersea** [comment]
Nice!  The left hand doesn't know what the right is doing.......  :)

I find popups in the middle of the map annoying, especially something as long as this one.  Maybe I will make the area under the info window opaque or partially transparent so that you can read it all, even if it overlaps the other things in the panel.
